# Generated by Django 3.1.7 on 2021-05-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(verbose_name='Ссылка на Amazon'),
        ),
    ]
